#! /bin/bash
# shell script for calculating MPI-monte Carlo multiple times - kind of hacky :()
for ((i=1;i<=100;i++)) do
    for ((j=1;j<=5;j++)) do
        mpiexec -n 4 ./parallel_monte_carlo $((i*100000))
        if [ $j -lt 5 ]; then
            printf "," >>./results/parallel_monte_carlo_integral # add delimiter
            printf "," >>./results/parallel_monte_carlo_timing
            printf "," >>./results/parallel_monte_carlo_n_values
        fi
    done
  printf "\n" >>./results/parallel_monte_carlo_integral # create rows
  printf "\n" >>./results/parallel_monte_carlo_timing
  printf "\n" >>./results/parallel_monte_carlo_n_values
done
